### ISSUE TITLE
iframe embed option

### ISSUE THREAD

**Issue by jackparmer** [plotly/dashboards.ly#1]
We're starting to get emails like this:

![image](https://cloud.githubusercontent.com/assets/1865834/10343954/a53e1a2e-6cee-11e5-9131-732da4988d8d.png)

Could also add this to:

http://help.plot.ly/embed-graphs-in-websites/

**Comment by chriddyp** [comment]
hm cool. I'll start writing out docs.

**Comment by chriddyp** [comment]
added these to the docs
