### ISSUE TITLE
Issue with 'DRAG TO REARRANGE'

### ISSUE THREAD

**Issue by enolette** [plotly/dashboards.ly#38]
After creating several rows of charts, the drag to rearrange function will not work -- 7/8th row. 

Thanks, 
Eric

**Comment by Kully** [comment]
I just played around with a dashboard with 9+ rows in both Safari and Chrome, and the functionality is working just fine: I can drag and drop the plots all around the dashboard with no problem.

Can I close the issue or should we investigate a little more? @chriddyp @jackparmer

**Comment by jackparmer** [comment]
@Kully I think we can close this. dashboards.ly users should be using https://plot.ly/dashboard/create now anyway. We're not support dashboards.ly anymore, except for On-Premise customers, since https://plot.ly/dashboard/create contains all the same features and is a massive improvement.

**Comment by enolette** [comment]
Thanks! this issue is a bit old and you guys have moved onto other dashboards
